baseURL = "https://infoiyo.cc/"
languageCode = "en"
title = "INFOiYo"
theme = "hugo-texify3"
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = false
rssLimit = 10

[pagination]
  pagerSize = 10

[taxonomies]
  tags = "tags"
  categories = "categories"

[params]
  title = "INFOiYo"
  author = "RAFSuNX"
  description = "Your blog description here"
  footnote = """
  Powered by <a class=link href=https://github.com/RAFSuNX target=_blank rel=noopener>RAFSuNX</a> | 
  Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
  """
  customCSS = []
  customJS = []
  dateFormat = "2 January 2006"
  emphasisWithDots = true
  toc = true
  rootFontSize = "105%"
  math = true
  enableDuckDuckGoSearchBox = true
  numberedSubtitles = true

  [params.sharingbuttons]
    facebook = true
    twitter = true
    email = true
    linkedin = true
    reddit = true
    whatsapp = true
    hackernews = true
    telegram = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[markup.goldmark.renderer]
  unsafe = true
