baseURL = "https://infoiyo.cc/"
languageCode = "en-us"
title = "INFOiYo"
theme = "hugo-narrow"

[pagination]
  pagerSize = 10

[params]
  description = "Your blog description here"
  author = "INFOiYo"
  keywords = ["blog", "INFOiYo"]
  images = ["images/og-image.jpg"]
  colorScheme = "system" # system, light, dark

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[markup.goldmark.renderer]
  unsafe = true